### ISSUE TITLE
Bauteile für v00.03.12

### ISSUE THREAD

**Issue by Ventusfahrer** [openbikesensor/openbikesensor.github.io#104]
Eine Excel-Liste der benötigten Bauteile wäre sehr sinnvoll.
Wenn eine solche exisitert, wäre ein Link dorthin ebenso sinnvoll.

Vielen Dank!

**Comment by notudu** [comment]
Wie in meinem Issue beschrieben: Stückliste mit Bauteilnummer (z.B. R7)

**Comment by opatut** [comment]
https://www.openbikesensor.org/docs/hardware/v00.03.12/parts/
