### ISSUE TITLE
HLRS Portal-URL aus Dokumentation entfernen

### ISSUE THREAD

**Issue by benbonn** [openbikesensor/openbikesensor.github.io#148]
Im unten aufgeführten Absatz funktioniert der Link nicht. 
 
> Der API-Key aus dem Settings-Menü des eigenen Accounts im Portal [openbikesensor.hlrs.de](https://www.openbikesensor.org/docs/user-guide/configuration/minimal/openbikesensor.hlrs.de) muss hier eingegeben werden. Wichtig: Speichern nicht vergessen.

**Comment by opatut** [comment]
Das HLRS-Portal wurde abgeschaltet und wird auch für die meisten nie wieder relevant werden. Die URL sollte trotzdem aus der Doku verschwinden ;) Ich habe mal den Titel entsprechend geändert. Danke für den Hinweis, @benbonn !
