### ISSUE TITLE
PDF export

### ISSUE THREAD

**Issue by boldt** [openbikesensor/openbikesensor.github.io#3]
PDF export: https://idratherbewriting.com/documentation-theme-jekyll/mydoc_generating_pdfs.html

Depends on #2

**Comment by opatut** [comment]
We can now export by PDF through using the print views of a chapter (link on the right), then printing to file. It mostly generates pretty good content, the theme supports printing, and we can adjust it further if we want through media-queries in CSS. I think a dedicated PDF export feature is not really needed for now, it will never look as good as a manually maintained document anyway...
