### ISSUE TITLE
Licensing of website content

### ISSUE THREAD

**Issue by opatut** [openbikesensor/openbikesensor.github.io#35]
I don't find a license file. We should fix this.

I guess CC-BY or CC-BY-SA would be good options, but this is usually a rather lengthy discussion. How do we want to do it? Also, we'll have to get confirmation from each contributor so far, as well as all photographs and possibly models (are there people's hands in the pictures somewhere?).... urgh.

Anyway, it needs to be done.

**Comment by amandel** [comment]
Applies to all our content :-/

**Comment by opatut** [comment]
The community has agreed to suggest LGPL-3.0 for all content, including this website.
