### ISSUE TITLE
Buttons auf /community

### ISSUE THREAD

**Issue by ChrizKu** [openbikesensor/openbikesensor.github.io#41]
Wären Buttons auf der [Community-Seite](https://github.com/openbikesensor/openbikesensor.github.io/blob/main/content/en/community/_index.md) passender/schöner (wie bei /about bzw. Startseite) oder ist das absichtlich lediglich ein Textlink?
Sind Buttons kompatibel/vorgesehen mit `blocks/feature`?

**Comment by opatut** [comment]
No idea, this is what docsy provided I think. But we can customize everything. If you want, you can exchange it.

**Comment by opatut** [comment]
@ChrizKu do you want to do this yourself?
