### ISSUE TITLE
Page editing does not work

### ISSUE THREAD

**Issue by tyll** [openbikesensor/openbikesensor.github.io#75]
The links to edit the page in GitHub do not work:

The link "Diese Seite bearbeiten" on https://www.openbikesensor.org/docs/ links to https://github.com/openbikesensor/openbikesensor.github.io/edit/main/content/de/docs/_index.de.md which does not work because of the `/de` directory that does not exist in the repository. It might be related to this setting: https://github.com/openbikesensor/openbikesensor.github.io/blob/main/config.toml#L69 - but the English version at https://www.openbikesensor.org/en/docs/ shows the same problem and there is no corresponding setting for that in the toml file.

**Comment by opatut** [comment]
This problem is caused by the theme assuming the folder structure incorrectly, see google/docsy#402.

I've fixed it by copying over the broken file and overriding it with custom logic that doesn't build a wrong URL. See #76.
