### ISSUE TITLE
Make sure all images are scaled with imgproc or slider shortcodes

### ISSUE THREAD

**Issue by boldt** [openbikesensor/openbikesensor.github.io#9]

**Comment by tobst** [comment]
Or reduce all pictures to 1000px and 94% quality as jpg?

**Comment by opatut** [comment]
Hugo handles this with the used shortcodes. We just have to go through every image and every file and make sure we use the `imgproc` shortcode and provide reasonably sized input images (can be maybe ~2000px wide at good quality). imgproc scales it down to I think 75% quality and the requested dimensions, which is usually 50-100kB per image. That's fine :)
