### ISSUE TITLE
Update hugo

### ISSUE THREAD

**Issue by opatut** [openbikesensor/openbikesensor.github.io#90]
Put the current version also in the readme.

Add a hint that updating is okay if it still works, and that the readme and pipeline file have to be updated for that.

**Comment by madiko** [comment]
Additional thought: It would be wise to check wether the respective hugo version and our theme are working together. It's not unsual, that a theme must be adapted, too.

**Comment by opatut** [comment]
Good thought, @madiko. I'll take care of that today. Luckily, we can specify the exact theme version since it is implemented as a submodule. So we have full control here.
