### ISSUE TITLE
Hugo fails: failed to resolve output format "print"

### ISSUE THREAD

**Issue by pReya** [openbikesensor/openbikesensor.github.io#97]
When I try to run Hugo (both locally and in Docker), it fails with the following error:

```shell
➜  openbikesensor.github.io git:(main) ✗ hugo server -D                  
Error: from config: failed to resolve output format "print" from site config
```

I don't know much about Hugo. Google didn't turn up a lot, either. Any ideas what this might be?

Running latest MacOS and latest Hugo version (`hugo v0.87.0+extended darwin/amd64`).

**Comment by SubOptimal** [comment]
Maybe you need to update the submodules

```
git submodule update --recursive
```

**Comment by opatut** [comment]
I think this did solve the issue.
